### ISSUE TITLE
Instagram Pictures & Top Posts

### ISSUE THREAD

**Issue by ltitensor** [voveson/crayons-and-cairns#3]
I'm sure you already have this in your mind but I thought i'd throw it on here anyway.

Reminder for the Instagram feed on the side and the top 3 most popular posts.

**Comment by voveson** [comment]
I finally -- after much tribulation -- got the Instagram feed working.  Let me know what you think. The script I wrote will pull in your most recent 9 pictures.

For "top posts", do you want to be able to manually select which posts will be displayed in the sidebar?  Or would you prefer to use a plugin to select posts for you?  And do you have an idea of how you'd like them displayed?  I assume we'll show the post's featured image and title... @ltitensor @smartash

**Comment by smartash** [comment]
Okay, I saw this one and it was one of those days that you think you've commented and then find out you just thought real hard about it.  :)  Anyhoo...  The instagram feed looks great!  and I'm sorry it was so tribulatious.  I don't think that's a real word.  BUT... I think we want a plug in that will show the top posts based on page views... or maybe on comments?  I don't know.  I don't know how i'd like them displayed because I don't really know what my options are.

**Comment by voveson** [comment]
Well the tribulation had very little to do with actually writing the code to pull in pics from Instagram.  It ended up being an issue with my server that hosts the beta site -- it just took me a while to figure that out :+1: 

I'll take a look at what our options are for top-posts plugins and put something up.
